# Generated by Django 4.0.3 on 2022-03-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ekko',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='ekko',
            old_name='bio',
            new_name='ekko',
        ),
        migrations.RenameField(
            model_name='ekko',
            old_name='verified_artist',
            new_name='verified_ekko',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='img',
        ),
        migrations.RemoveField(
            model_name='ekko',
            name='name',
        ),
        migrations.AddField(
            model_name='ekko',
            name='source',
            field=models.CharField(default='anonymous', max_length=250),
        ),
        migrations.AddField(
            model_name='ekko',
            name='user',
            field=models.CharField(default='sam-aum', max_length=100),
        ),
    ]
