# Generated by Django 4.0.3 on 2022-03-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_ekko_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ekko_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='comment', max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ekko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.ekko'),
        ),
    ]
