# Generated by Django 4.0.3 on 2022-03-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_comment_ekko_comment_comment_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='verified_ekko',
        ),
    ]
